import React, { useEffect, useState } from 'react';
import AdminSidebar from '../components/admin/AdminSidebar';
import UnionReviewCard from '../components/UnionReviewCard';
import { useLanguage } from '../context/LanguageContext';
import { createAdminUnionReview, fetchAdminUnionReviews, fetchFaculties, fetchMajors, fetchSubjects, type FacultyItem, type MajorItem, type SubjectItem, type UnionReviewItem } from '../lib/http';

const levels = ['L1','L2','L3','M1','M2'];
export default function AdminUnionReviewsPage() { const { t } = useLanguage();
const [reviews,setReviews]=useState<UnionReviewItem[]>([]); const [faculties,setFac]=useState<FacultyItem[]>([]); const [majors,setMaj]=useState<MajorItem[]>([]); const [subjects,setSub]=useState<SubjectItem[]>([]);
const [form,setForm]=useState<any>({ organizer:'UNEM', level:'L1' });
useEffect(()=>{void Promise.all([fetchAdminUnionReviews(),fetchFaculties(),fetchMajors(),fetchSubjects()]).then(([r,f,m,s])=>{setReviews(r.data.reviews??[]);setFac(f.data.faculties??[]);setMaj(m.data.majors??[]);setSub(s.data.subjects??[]);});},[]);
const filteredMaj=majors.filter((m)=>!form.facultyId||m.facultyId?._id===form.facultyId); const filteredSub=subjects.filter((x)=>(!form.facultyId||x.facultyId?._id===form.facultyId)&&(!form.majorId||x.majorId?._id===form.majorId));
return <div className='grid gap-4 md:grid-cols-[240px_minmax(0,1fr)]'><AdminSidebar /><div className='space-y-4'><div className='card-surface p-5'><h1 className='section-title'>{t.unionReviews.adminTitle}</h1><div className='mt-4 grid gap-3 md:grid-cols-2'>{['title','description','location'].map((k)=><input key={k} className='w-full' placeholder={(t.unionReviews as any)[k==='title'?'titleField':k]} value={form[k]??''} onChange={(e)=>setForm({...form,[k]:e.target.value})} />)}<select value={form.organizer} onChange={(e)=>setForm({...form,organizer:e.target.value})}><option>UNEM</option><option>UGEM</option></select><select value={form.facultyId??''} onChange={(e)=>setForm({...form,facultyId:e.target.value,majorId:'',subjectId:''})}><option value=''>{t.unionReviews.faculty}</option>{faculties.map((f)=><option key={f._id} value={f._id}>{f.nameFr}</option>)}</select><select value={form.majorId??''} onChange={(e)=>setForm({...form,majorId:e.target.value,subjectId:''})}><option value=''>{t.unionReviews.major}</option>{filteredMaj.map((f)=><option key={f._id} value={f._id}>{f.nameFr}</option>)}</select><select value={form.level} onChange={(e)=>setForm({...form,level:e.target.value})}>{levels.map((l)=><option key={l}>{l}</option>)}</select><select value={form.subjectId??''} onChange={(e)=>setForm({...form,subjectId:e.target.value})}><option value=''>{t.unionReviews.subject}</option>{filteredSub.map((f)=><option key={f._id} value={f._id}>{f.nameFr}</option>)}</select><input type='datetime-local' value={form.startsAt??''} onChange={(e)=>setForm({...form,startsAt:e.target.value})} /></div><button className='primary-btn mt-3' onClick={async()=>{const {data}=await createAdminUnionReview(form);setReviews((p)=>[data.review,...p]);}}>{t.unionReviews.publish}</button></div><div className='grid gap-3'>{reviews.map((r)=><UnionReviewCard key={r._id} review={r} onUpdate={()=>{}} admin />)}</div></div></div>; }
